version: '3'
services:
  frontend: # React client
    tty: true
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend: # Django server
    build: ../chess-plus-plus-backend
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000